# Generated by Django 5.1.5 on 2025-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_chat_messag_read_8afd86_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
