# Generated by Django 5.1.5 on 2025-04-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_groupmessage_read_groupmessage_read_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='read',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='read_at',
        ),
    ]
