# Generated by Django 5.1.5 on 2025-04-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_groupmessage_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='read_by',
        ),
    ]
